# SESSION 1: Python

By **Miquel Torrens i Dinarès**

*Barcelona School of Economics* –
*Data Science Center*

January 4, 2022

---
## 1. Preliminaries

### 1.1 Getting started

We will be working in Google Colab throughout the course. You can find more details about Colab [here](https://https://colab.research.google.com/notebooks/basic_features_overview.ipynb).

There are different styles to writing code, but try to stick consistently to a (sensible) style guide: it is essential that the code not only works but is also understandable by everyone. The "official" guide for `python` can be founde here:

* Style guide: https://www.python.org/dev/peps/pep-0008/

Rules to code properly are fairly common sense, just like those of natural language. You can make them your own (within reason), the important part is to be **consistent**.

### 1.2 Printing

It can be useful to *print* what we are running on the console, this can be done with the built-in `print` command. You might have noticed that Colab notebooks automatically display the value of the last expression in a cell when you execute it, so you don't need to print that.

In [ ]:
# Colab automatically prints "y" to "out", 
# but we need to manually print "x" if we want to see it
x = 15 / 2
print(x)
y = x > 2
y

We may want to use placeholders to print strings. There are a number of ways to do that.

In [ ]:
a = 15
b = 2
c = 2
'%i divided by %i is %.2f, and it is %s that this is greater than %i' % (a, b, a/b, (a/b) > c, c)

'15 divided by 2 is 7.50, and it is True that this is greater than 2'

We will go into what these objects are shortly.

---
## 2. Basic data types

Here we highlight the most important native operations you can apply to basic objects in `python`. We will go to a lower level of detail of the structure of these processes in the `R` session later in the afternoon.

### 2.1 Numerical values

In [ ]:
# Assignment
a = 10  # 10

# Increment/Decrement
a += 1  # 11 (a = a + 1)
a -= 1  # 10 (a = a - 1)

# Operations
b = a + 1  # 11
c = a - 1  # 9

d = a * 2  # 20 
e = a / 2  # 5 
f = a % 3  # 1 (remainder)
g = a ** 2  # 100 (exponentiation)

# Operations with other variables
d = a + b  # 21

### 2.2 String values

You can concatenate strings together with the `+` operator:

In [ ]:
"Adding" + " " + "strings" + " " + "is" + " " + "pasting"

'Adding strings is pasting'

The built-in function `len` can be used to find the length of a string:

In [ ]:
len("four")

4

### 2.3 Logical values

We can evaluate the relationships between different types of data in `python`. The output of such comparisons/operations are boolean variables. Some examples:

In [ ]:
# Comparing numbers
x = (1 >= 2)  # greater or equal
y = (1 == 2)  # equal
w = (1 != 2)  # different

# Parentheses are not required, but they help readability
x = (1 <= 2) and (1 > 0)  # both statements are true
y = (1 >  2) or  (1 < 3)  # at least one statement is true

# It is good practice to use "is" instead of == for checking for NoneType:
x = None
y = x is None
z = x is not None
print(y)
print(z)

True
False


### 2.4 Lists

Lists are one of the simplest multi-value objects. They are created with square brackets:

In [ ]:
a_list = ["This", "is", "a", "list", "of", "strings"]

Here you can see we created a list of strings. We can also create a list of integers:

In [ ]:
num_list = [1, 5, 10]

Lists in `python` need not be homogenous, you can mix object types:

In [ ]:
mix_list = ['a', 'b', 1, 2, 3, True, None]

Sometimes you want to access individual elements from a list. You can do this using square brackets together with the index of the element:

In [ ]:
mix_list[0]  # first element

'a'

Notice that the first element is indexed at `0`, the second element at `1`, and so on. You can also access a contiguous range of elements:

In [ ]:
mix_list[1:3]  # second item (index 1) and third item (index 2) only!

['b', 1]

You can also use negative indices to access items from the end. For example, the last item:

In [ ]:
num_list[-1]

You can concatenate multiple lists together with the operator `+`:

In [ ]:
num_list + [40, 50, 60]

[1, 5, 10, 40, 50, 60]

And you can check for membership with the operator `in`:

In [ ]:
"abc" in ["abc", "def", "ghi"]

True

### 2.5 Tuples

Tuples are created with parenthesis:

In [ ]:
x = ("foo", 1)

But can also be created without any perenthesis, implied by the comma:

In [ ]:
x = "foo", 1

Elements in the tuple are also accessed via the index (like lists).

Lists can be used most places that a tuple is used, so it can be confusing what the difference is between the two. Besides technicalities, the following rules can help you decide when to use a tuple and when to use a list:

* `list`: many elements (potentially), unknown number, relatively homogenous, mutable.
* `tuple`: few elements, fixed number, completely heterogeneous, immutable (fixed).

The name comes from here: double, triple, quadruple... This hints that they should be of fixed length.
Since their length is fixed, we often use them with destructuring:

In [ ]:
name,num = x

Now the variable `name` contains the value `"foo"` and the variable `num` contains the value `1`.

### 2.6 Dictionaries

Dictionaries are another basic type in `python`. They are *associative* data structures. Like a standard dictionary, python dictionaries associate a `KEY` with a `VALUE` and are created with the `{`, `}` operators:


In [ ]:
player = {"name": "Jane", "score": 10000}

You can access the value via the *key*, and set it in a similar way:


In [ ]:
player["name"]
player["name"] = "Jane Smith"

Each key can only have one value. In the above example, we have overwritten the original `"name"`-key with a new value.

In [ ]:
# Create a list whose elements are of type dictionary
# Each element on the list is a player, and each player has three attributes.
players = [{"name": "John", "score": 100, "likes": ["R"]},
           {"name": "Jane", "score": 10000, "likes": ["python"]},
           {"name": "Stephen", "score": 55, "likes": ["julia"]}]
print(players[0])

# We can fetch elements of the dictionary
players[0]['name']
players[0].get('name')

### 2.7 Properties of an object: instances, attributes and methods

Objects in `python` have *classes*. For example:

In [ ]:
new_list = [1, 2, 3]  # Create a list
type(new_list)  # This function tells you the type of object

list

`new_list` is an ***instance*** of the class `list`. Instances can have ***attributes***. These attributes are just properties that are attached to the instance. They are accessed with dot notation:

In [ ]:
# I define my own class: custom types
class invented_class: 
    name = "John"
    score = 100
    def show(self): 
        print (self.name) 
        print (self.score) 
 
# Create an object of this new class
new_obj = invented_class()
print(type(new_obj))
print(new_obj.score)

Here `new_obj` is an instance of the class `invented_class`, and it has attributes `name` and `score`.

If the attribute happens to be a function, we call it a ***method***. Methods are functions that have a special purpose: they interact with the instance itself in some way.

---
## 3. Iterables and control flow

### 3.1 Iterate over elements of an object (`for`-loops)

You may want to perform an operation for each element in an *iterable* object, and (possibly) store the result of such operation. We do that by *looping* over this object operating on every of its elements sequentially.

In [ ]:
vector = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
squared = []
for num in vector:
    squared_num = num ** 2
    squared = squared + [squared_num]

squared

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

The structure of the loop is critical and always the same: 

In [ ]:
## NOT RUN
for ELEMENT in EXISTING_OBJECT:  # Use "for", "in" and ":"
    operation_on(ELEMENT)  # Indent 4 spaces (MANDATORY)

# Loop ENDS when indentation is over
## END NOT RUN

`for`-loops are applicable to every instance of an iterable object class: `list`, `tuple`, `dictionary`.

### 3.2 Operations on lists

There are three main operations we perform on a list:
1. Aggregate (*reduce* operation)
2. Apply a function to each element (*map* operation)
3. Select elements (*filter* operation)

We illustrate these with some examples.

In [ ]:
# 1. AGGREGATION
# Summing the numbers in a list: 
nums = [30, 1, 4, 3, 10.5, 100]
total = 0 
for num in nums:
    total += num
    
print(total)

# 2. APPLY A FUNCTION 
# Squaring each number in a list
nums = [30, 1, 4, 3, 10.5, 100]

# This is called a "list comprehension"
# and is the python way to apply a function to 
# every element in a list
squared_nums = [num ** 2 for num in nums]
squared_nums

# 3. FILTER
# Remove all values less than 18:
ages = [0, 3, 21, 45, 10, 97]
adults = [a for a in ages if a > 17]
adults

### 3.4. Control flow

Sometimes you may want to operate only if the object satisfies some relevant criteria, for example make a decision based on some condition holds. In these cases we use `if`-statement operations.

In [ ]:
gender = "male"
age = 20 

# Start of if-statement
if gender == "female":
    if age > 18:
        print("woman")
    else: 
        print("girl")
elif gender == "male":
    if age > 18:
        print("man")
    else: 
        print("boy")
else:
    print("other")


man


Again, the structure of an `if`-statement is always the same, so it is essential that we use it correctly

In [ ]:
## NOT RUN
if BOOLEAN:  # Use: "if", ":" and supply a boolean condition
    ACTION1a  # Indent with 4 spaces
    ACTION1b
elif BOOLEAN:  # Second layer to "if" (else-if)
    ACTION2
else:  # Rest of scenarios (make sure all contingencies are covered)
    ACTION3

## END NOT RUN

Like in `for`-loops, statements are closed by indentation.

---
## 5. Functions

### 5.1 Coding functions

Functions (may) use an input to produce an output through a set of operations.

In [ ]:
## NOT RUN
def function_name(input):  # Use "def", parenthesis and ":"
    operations
    return output  # End with "return"

## END NOT RUN

For example, here is a function that takes a number, and returns its square:

In [ ]:
def squared(x):
    return x**2

squared(7)

16

Here is a more general function that takes a number and a power and returns the number to that power:

In [ ]:
def power(x, n):
    return x ** n

power(4, 3)

64

Here is a function that returns the minimum and the sum of a list of numbers:

In [ ]:
def min_sum_fun(x):
    minx = x[0] if len(x) > 0 else None
    sumx = 0.0  
    for val in x: 
        if val < minx:
            minx = val
        sumx += val 
    return minx, sumx  # Notice multiple outputs (technically a tuple)


Now we can call that function:

In [ ]:
m, s = min_sum_fun([1, 5, 0.3, -1])  # Destructuring
w = (m, s) = min_sum_fun([1, 5, 0.3, -1])  # You can assign directly to a tuple

print(m)
print(s)
print(w)
print(type(w))

-1
5.3
(-1, 5.3)
<class 'tuple'>


### 5.2 Map, reduce

[PENDING]

---
## 6. Modules and imports

*Modules* are `python` files, recognised in the computer as `<filename>.py`. Data and methods defined in the module can become part of the namespace by using `import`.

In [12]:
x = sin(5)  # The "sin" function does not exist

In [8]:
from math import sin  # You need to "import" it
x = sin(5)
print(x)

-0.9589242746631385


There are some other useful tricks to import data and methods:

In [11]:
from math import sin  # Imports a single function
from math import sin as sinus  # Nickname, useful when you import something with a long name
print(sinus(3))

import math  # Imports the module in the namespace, methods can then be accessed e.g.
print(math.sin(3))

0.1411200080598672
0.1411200080598672


Let us discuss here a couple of fundamental imports in `python`:

### 6.1 `numpy` (Numerical Python)

*   User's manual: https://numpy.org/doc/stable/

This is Python's stack for scientific computing. The fundamental new data type is that of a **`numpy` `array`**, Python's matrix-type object, which is used in the majority of its data analysis, statistics and machine learning modules.

These arrays contain data all of the same type (dtype), numerical of many types or boolean:

In [39]:
# Import module 
import numpy as np  # usually imported with name "np"

# Creating an array
A = np.array([[1, 2, 3, 4, 5, 6], 
              [42, 53, 43 ,62, 7, 4], 
              [-3, -1, -4 ,-8, -52, -4], 
              [10, 0, 4 , 1, 0, 1]])

We can access the elements in an array using multi-index notation (counting starts from 0, slicing `a:b` is inclusive:exclusive, negative indices, etc.)

In [40]:
print(A)
# Print from row 3 onwards, columns 3 and 5
print(A[2:, [2, 4]])

[[  1   2   3   4   5   6]
 [ 42  53  43  62   7   4]
 [ -3  -1  -4  -8 -52  -4]
 [ 10   0   4   1   0   1]]
[[ -4 -52]
 [  4   0]]


In [42]:
# Attributes
A.shape  # dimension
A.min()  # minimum (you can similarly use max, sum, etc.)
A.diagonal()  # diagonal
B = A.transpose()  # transposing
C = A.reshape(6, 4)  # rearrange values to change dimension (CAREFUL!)
print(A.shape)
print(B.shape)
print(C.shape)
A.dot(B)  # dot-product (with array B)


(4, 6)
(6, 4)
(6, 4)


array([[   91,   584,  -333,    32],
       [  584, 10331, -1227,   658],
       [ -333, -1227,  2810,   -58],
       [   32,   658,   -58,   118]])

#### 6.1.1. `array` operations

Mathematical symbols take on mathematical meanings in `numpy`, and so the `+` operator between two `np.array` just tries to add them together elementwise (it works differently to `list`-type objects). To concatenate you need a specific function.


In [45]:
# Numpy array addition: 
a, b = np.array([1, 2, 3]), np.array([4, 5, 6])
print(a + b)  # Addition
print(np.concatenate([a,b]))  # Concatenation

[5 7 9]
[1 2 3 4 5 6]


### 6.2 `pandas` (Panel Data Structures)

This is the module in Python for doing rectangular-data management, analysis and plotting. It provides tools to read and write external data.


In [8]:
import pandas as pd  # Usually imported with name "pd"

file_path = "https://raw.githubusercontent.com/barcelonagse-datascience/academic_files/master/data/tips.csv"
tips = pd.read_csv(file_path)  # read_csv allows importing .CSV files
print(tips.head(5))  # head gives first rows (arg = number of rows)

# Data formats in pandas
print(type(tips))
print(type(tips['tip']))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


There are the two basic data formats in `pandas`: `Series` and `DataFrame`. A `Series` is the equivalent to a vector in linear algebra. A `DataFrame` is the equivalent to a rectangular data structure. These types are equipped with several attributes useful for data management and analysis. In the tips example, the variable object `tips` is a `DataFrame`, while any individual column would be a `Series`.

---
## 7. Structured data operations (`pandas`)

### 7.1 `Series`

They are accessed via their index, which can be either a number or a string. They are typically obtained by reading a dataset from an external file or when operating on a `DataFrame`, but they can be defined manually:

In [ ]:
# Here no indices are specified (there are defaults)
a_series = pd.Series([1, 15, -5, None, 4, 123, 0, 78, 0, 1, -4])
a_series

In [13]:
# Accessing a certain value via the index
a_series[0]

1.0

In [ ]:
# .values returns a numpy.ndarray of the values
a_series.values
a_series.index, my_series.index.values

In [ ]:
# You can overwrite the index directly: 
a_series.index = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]
a_series

Accessing values via the index can be very useful, but sometimes you want to access the values as though they were a Python list. In other words "I want the first value!", without having to know the name of the label. This can be achieved with `.iloc`:


In [ ]:
a_series.iloc[0], a_series["a"], a_series.iloc[-1]


In [ ]:
# This just resets the index to be as we found it originally
a_series = a_series.reset_index(drop = True)
x = a_series.sort_values()

x[0], x.iloc[0] 
# the indices remain, so x indexed by 0 is 1
# the ordering changes, so the first element of x is -5.0, the minimum

As usual one should explore the attributes of any python object one ends up working with. We have already accessed the `.index` and `.value`. Some other that are worth highlighting:

*   `.map`
*   `.corr`
*   `.describe`
*   `.hist`
*   `.plot`
*   `.size`
*   `.value_counts`
*   `.sort_values`

For example:

In [ ]:
tips.describe()

### 7.1.1 Operations with `Series`

`Series` are `numpy` arrays behind the scenes, so we can compute element-wise functions on one series or several series at the same time. The result is another series with data type depending on the type of operations performed.


In [25]:
series1 = pd.Series([1, 3, 5, 7])
series2 = pd.Series([0, 10, -1, 6])

series3 = 2 * series1 + abs(series2)
series4 = series1 > series2 

print(series3)
print(series4)
# Take a look at the different Series objects!

0     2
1    16
2    11
3    20
dtype: int64
0     True
1    False
2     True
3     True
dtype: bool


What goes on in the previous examples is more subtle than it looks. How does Python know which elements from each series to join in the required operation together? What happens is that the indices happened to be the same. So when we ask something like

`series3 = series1 + series2`,

Python looks for entries in each series with the same index and then does an elementwise summation that it stores in a like-wise index in Series 3.

Consider instead the following example:


In [ ]:
series1 = pd.Series([1, 10], index=["A", "B"])
series2 = pd.Series([4, -1], index=["C", "D"])
series3 = series1 + series2
print(series3)

This aspect makes it very easy to work with series that we have sorted or manipulated otherwise; there is always the address to access a value. This helps prevent accidentally combining values we didn't mean to combine!

In [ ]:
# accesing by list of index labels
a_series.index = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K"]
x = a_series[["A", "K"]]

In [ ]:
a_series

In [ ]:
x

In [ ]:
# Getting a boolean-valued series by checking a condition
choose = (a_series == 0.0)
choose

In [ ]:
# Notice the index of x is a SUBSET of the index of "a_series"
# This can be useful when needing to relate values back to the original "a_series"!
x = a_series[choose]
print(x)
# or the complement
a_series[~choose]

We often use boolean masks to filter data in Pandas. We also get special boolean algebra operators to use in `numpy`/`pandas`, distinct from the and/or/not you will use in regular Python: `&` (AND), `|` (OR), `~` (NOT).


### 7.1.2 Missing values

A series object in `pandas` can help us deal with missing data. We already see very naturally how data management can quickly lead to missing data.

In [ ]:
series3 = series1 + series2
print(series3)

What happened there is that in the operation labels could not be matched, so `pandas` tried to sum a numeric value with missing value, the result of which is a missing value.
The way to manually specify in `pandas` that a value is missing is to use `None`, as below:

In [38]:
temp = pd.Series([1, None, 2])
print(temp)

0    1.0
1    NaN
2    2.0
dtype: float64


`pandas` coerces `None` values to `NaN` ("Not a Number") values. We can create boolean masks on the basis of such values. The way to identify NaN or None values in a Series is to use either of the equivalent two attributes: `.isna()` and `.isnull()` (existing the opposite `.notna()` and `.notnull()`).

In [43]:
temp.isna()
temp.isnull()

0    False
1     True
2    False
dtype: bool

In [44]:
temp.notna()
temp.notnull()

0     True
1    False
2     True
dtype: bool

### 7.2 `DataFrame`

This is `pandas` model for rectangular data. Operationally similar to a dictionary of `Series`; each column of the `DataFrame` is a `Series` object, and comes with all the attributes/methods of a `Series`. An implication is that within each column the data type is common; across columns this can change.

In [ ]:
# Recall our "tips" dataset
tips.head(5)  # The first method of our DataFrame object

In [49]:
# the other important attribute: name of rows and columns
print(tips.shape)
print(tips.index)
print(tips.columns)

(244, 7)
RangeIndex(start=0, stop=244, step=1)
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')


To access the columns of a `DataFrame` there are two standard ways.

In [ ]:
tips.tip  # As if it were a method (NOT recommended)
tips["size"]  # As if it were a named index (RECOMMENDED)

The latter is recommended because, for example, the column `size` cannot be accessed via the first option (it would be confused with the method `.size`). The result of this operation is an object of type `Series`.

We can access various columns at a time, supplying a list of columns, obtaining a dataframe with the same index as the original and columns the chosen subset.

In [ ]:
tips[["tip", "size", "sex"]].head(5)

Similarly, you can access rows instead of columns with the same philosophy.

*   Using a list of index labels: `tips.loc[ [index1, index2, ...] ]`
*   Using a list of integer index location (i-loc): `tips.iloc[ [integer1, integer2, ...] ]`



In [ ]:
# Accessing rows AND columns!
# Example of 2-dimension loc
tips.loc[[1, 3], ['sex', 'smoker']]

In [ ]:
# Accessing rows AND columns!
# Example of 2-dimensional iloc
tips.iloc[[1, 3], 2:5]

Note that certain operations are exchangeable: the 3rd element of column "sex" can be obtained with either of the following ways:

In [ ]:
tips.sex[2]  # Access col as series, then the 3rd element of that
tips.loc[2, "sex"]  # Access the entry in DF by giving the index labels of row and col
tips.loc[2]["sex"]  # Accessing the whole row as a series, then using the column name as index label

As with `Series`, we can use a boolean-valued series to index a `DataFrame` provided the share the same index labels. The simplest instance of this is to use series produced as boolean masks of columns of the dataframe. The output of this *filtering* operation is a dataframe with subset of rows corresponding to the `True` values in the boolean mask.

In [ ]:
tips[tips['sex'] == "Male"].head(5)

In [ ]:
tips[(tips['sex'] == "Male") & (tips['day'] == "Sun")].head(5)  # Multiple booleans ("&", "|", "~")

A `DataFrame` comes with several attributes for computing column-wise statistics and summaries. We highlight some of them:

*   `.boxplot` (check out the `by = ` option)
*   `.corrwith` and `.corr` (within and across `DataFrame`'s)
*   `.dot`
*   `.mean/median/max/quantile/sum`, etc.
*   `.sample`
*   `.sort_values`
*   `.unique`


### 7.2.1 `GroupBy`

This `DataFrame` method groups the `DataFrame` according to the values of a column, treating them as categorical values. It returns a groupby object.

In [ ]:
# Group tips DataFrame by size of table
by_size = tips.groupby("size")
print(by_size)

# If we coerce it to a list, we see something interesting: 
# it's basically a list of tuples
# The first element is the "category" variable, the second
# is a datafame. 
list(by_size)

In [75]:
list(tips.groupby("sex"))

[('Female',      total_bill   tip     sex smoker   day    time  size
  0         16.99  1.01  Female     No   Sun  Dinner     2
  4         24.59  3.61  Female     No   Sun  Dinner     4
  11        35.26  5.00  Female     No   Sun  Dinner     4
  14        14.83  3.02  Female     No   Sun  Dinner     2
  16        10.33  1.67  Female     No   Sun  Dinner     3
  ..          ...   ...     ...    ...   ...     ...   ...
  226       10.09  2.00  Female    Yes   Fri   Lunch     2
  229       22.12  2.88  Female    Yes   Sat  Dinner     2
  238       35.83  4.67  Female     No   Sat  Dinner     3
  240       27.18  2.00  Female    Yes   Sat  Dinner     2
  243       18.78  3.00  Female     No  Thur  Dinner     2
  
  [87 rows x 7 columns]),
 ('Male',      total_bill   tip   sex smoker  day    time  size
  1         10.34  1.66  Male     No  Sun  Dinner     3
  2         21.01  3.50  Male     No  Sun  Dinner     3
  3         23.68  3.31  Male     No  Sun  Dinner     2
  5         25.29  4.

In [77]:
# We can iterate through the groupby just like we would a list of tuples!
for sex, data in tips.groupby("sex"):
    print(sex)
    print(data.mean())


Female
total_bill    18.056897
tip            2.833448
size           2.459770
dtype: float64
Male
total_bill    20.744076
tip            3.089618
size           2.630573
dtype: float64


We `groupby` to perform *some* operation on each group, to *map* over the groups, applying a function to each element Very often this function is itself an aggregation (*reduction*). We want to somehow aggregate each group into a value or set of values that *describe* it.

To apply functions to each element of a `groupby`, we use `.apply`:


In [79]:
# Get the maximum bill by gender: 
def max_bill(df):
    return df['total_bill'].max()

tips.groupby("sex").apply(max_bill)

sex
Female    44.30
Male      50.81
dtype: float64

Many aggregation functions that exist on Series and `DataFrames` (`mean`, `max`, `min`, etc.) can be called directly via the groupby object:

In [81]:
print(tips.groupby("sex").max())
print(tips.groupby("sex").mean())

        total_bill   tip smoker   day   time  size
sex                                               
Female       44.30   6.5    Yes  Thur  Lunch     6
Male         50.81  10.0    Yes  Thur  Lunch     6
        total_bill       tip      size
sex                                   
Female   18.056897  2.833448  2.459770
Male     20.744076  3.089618  2.630573


We can actually `groupby` more than one column:

In [83]:
tips.groupby(["sex", "day"])['tip'].mean()

sex     day 
Female  Fri     2.781111
        Sat     2.801786
        Sun     3.367222
        Thur    2.575625
Male    Fri     2.693000
        Sat     3.083898
        Sun     3.220345
        Thur    2.980333
Name: tip, dtype: float64

### 7.2.2 Combining `DataFrame`'s

There are many ways to combine various `DataFrame`s into a new one, extending in many ways what we already saw for operations on `Series`. The main ways of doing this are:

*   **Concatenate**: paste row-column-wise and taking action on `NaN`s (this works more on the rectangular structure of the data)
*   **Merge**: combine `DataFrame`s using a common piece of information, e.g. an identifier column (this works more as a database operation)



In [84]:
# Concatenate
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"A": pd.Series([4]), "C": pd.Series([7])})
pd.concat([df1, df2], axis = 0)
# axis: 0 for pasting below, 1 for pasting on the side

A    B    C
0  1  4.0  NaN
1  2  5.0  NaN
2  3  6.0  NaN
0  4  NaN  7.0

In [85]:
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"A": pd.Series([4]), "C": pd.Series([7])})
pd.concat([df1, df2], axis = 1, join = "inner")  # "inner" join

A  B  A  C
0  1  4  4  7

In [86]:
# Concatenation is mostly used when the rows or columns are shared. 
# For example, you might have data with the same columns and want to concatenate them on axis 0:
# But note: what happened to the index? 
# We might want to reset it. 
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"A": pd.Series([4]), "B": pd.Series([7])})
df3 = pd.concat([df1, df2], axis = 0)
df3

A  B
0  1  4
1  2  5
2  3  6
0  4  7

In [87]:
# Similarly, you might have data with the same rows and different columns:
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"C": pd.Series([4]), "D": pd.Series([7])})
pd.concat([df1, df2], axis = 1)

A  B    C    D
0  1  4  4.0  7.0
1  2  5  NaN  NaN
2  3  6  NaN  NaN

In [88]:
# But note what happens if the rows do not align, and you concatenate on axis 1 (by rows):
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"C": pd.Series([7]), "D": pd.Series([10])})
pd.concat([df1, df2], axis = 1)

A  B    C     D
0  1  4  7.0  10.0
1  2  5  NaN   NaN
2  3  6  NaN   NaN

Let's go with merging now: `merge` is commonly used when your two `DataFrame`s must be connected and they do not share an index or columns. With merge we will connect two `DataFrame`s on some common piece of information, e.g. a common column. There are four types of `join` operations:

*   `inner`-join: **intersection** of *keys*
*   `outer`-join: **union** of *keys*
*   `left`-join: use *keys* from **left only**
*   `right`-join: use *keys* from **right only**

In [90]:
# Merging
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"A": pd.Series([3, 4]), "C": pd.Series([7, 8])})

# "on" defines on what piece of information the DataFrame's will merge
pd.merge(df1, df2, on = 'A', how = 'right')  # if column names differ, use "left_on" and "right_on"

A    B  C
0  3  6.0  7
1  4  NaN  8

In [91]:
pd.merge(df1, df2, on = 'A', how = 'left')

A  B    C
0  1  4  NaN
1  2  5  NaN
2  3  6  7.0

In [92]:
pd.merge(df1, df2, on = 'A', how = 'outer')

A    B    C
0  1  4.0  NaN
1  2  5.0  NaN
2  3  6.0  7.0
3  4  NaN  8.0

In [93]:
pd.merge(df1, df2, on='A', how = 'inner')

A  B  C
0  3  6  7

---
## 8. String manipulation

### 8.1 Simple operations

You may find yourself working with text data, a.k.a. strings. 

Strings are actually iterables, just like lists. They can be subset analogously:

In [95]:
x = "one python string"
x[4:10]

'python'

In [96]:
# You can also turn a string into a list of strings via the "split" method:
x = "one python string"
y = x.split(" ")
y == ["one", "python", "string"]

True

In [97]:
# The reverse is also possible via the "join" method:
space = " "
z = space.join(y)
z == x

True

You can also make everything lower (or upper) case, replace certain substrings with other substrings, and check for the existence of a substring with `in`:

In [101]:
z = "My Python String"
z.lower()

'my python string'

In [102]:
z.upper()

'MY PYTHON STRING'

In [104]:
w = z.replace("Python", "R")
print(w)
"Python" in w

My R String


False

There are many more easy-to-use, built-in tools for working with text data in Python. You can read more here:

*   https://docs.python.org/3/library/stdtypes.html#string-method

### 8.2 Regular expressions

A *regular expression* is a special sequence of characters that helps you match or find other strings or sets of strings, using a specialized syntax held in a pattern. Regular expressions are used in different languages, we'll also review them in the `R` session. Python uses the module `re` to deal with them.

Let's pretend we have an `html` text. Find **all** words tagged as bold (`<b>word</b>`) in `html`, turn them to italics (`<i>word</i>`) and add the word "freaking" before them.

In [107]:
import re

a_text = 'Why am I taking this <b>course</b>? I want to go back to the <b>holidays</b>.'

# Preffix 'r' is an indicator of regular expression
the_regex = r'<b>([a-z\s]+)</b>'
replacement = r'<i>freaking \1</i>'

# Function to replace a regular expression with another
re.sub(the_regex, replacement, a_text)

'Why am I taking this <i>freaking course</i>? I want to go back to the <i>freaking holidays</i>.'

Some helpful functions to manouvering with regular expressions with `re`:

*  `re.search(pattern, string)`: scan through `string` looking for locations where the regular expression `pattern` produces a match, and return a corresponding match object.
*  `re.match(pattern, string)`: if zero or more characters at the beginning of `string` match the regular expression `pattern`, return a corresponding match object.
*  `re.split(pattern, string)`: split `string` by the occurrences of `pattern`
*  `re.sub(pattern, repl, string)`: return the `string `obtained by replacing the leftmost non-overlapping occurrences of `pattern` in string by the replacement `repl`
*  `re.findall()`: search for *all* occurrences that match a given pattern

Regular expressions are relatively complex and there is a long list of combinations we can make, which are well outside the scope of this introduction. We limit to mentioning some special characters to form regular expressions:

*  `^`: Start of string
*  `$`: End of string
*  `.`: One character, no matter which (except line break)
*  `*`: match 0 or more repetitions of the preceding RE
*  `+`: match 1 or more repetitions of the preceding RE
*  `?`: match 0 or 1 repetition of the preceding RE
*  `{m,n}`: Causes the resulting RE to match from m to n repetitions of the preceding RE. The comma and the n are optional depending on the case
*  `|`: OR. E.g. A|B means match RE A or B
*  `(...)`: Matches whatever regular expression is inside the parentheses
*  `[]`: Defines a subset of characters to match
*  `\`: Either escapes special characters (permitting you to match characters like '*', '?', and so forth), or signals a special sequence (e.g. \s means a white space).
*  `\w`: Matches a word (letters only)
*  `\W`: Matches a word (letters and characters, equivalent to `[^a-zA-Z0-9_]`)

---
## 9. Some advanced concepts


### 9.1 Copy vs. assignment

Look at the following example:

In [5]:
a = [1, 2, 5]
b = a
b[2] = 10

In [ ]:
print(a)
print(b)

What happens is that really `a` and `b` point to the same place in the memory and share the same data. The way to create an object that will *copy* the data in a but not *share* the data with a is to use the method `copy()`.

In [1]:
a = [1, 2, 5]
b = a.copy()
b[2] = 10

In [ ]:
print(a)
print(b)

This goes a bit deeper into the concept how `python` uses memory in your computer, but it is important to have a grasp on it in order to avoid potential problems when memory becomes an issue.

In [3]:
a = [1, [2, 3], 5, 'abc'] 
b = a.copy()
b[1].append(100)

In [ ]:
print(a)
print(b)

Things become a little trickier when you deal with lists of lists, for this reason there is also the `deepcopy`. 

In [7]:
a = [1, [2, 3], 5, 'abc'] 
b = a.copy()
b[1].append(100)

In [ ]:
print(a)
print(b)

(What happened here is that both `a` and `b` still point to some deeper list `[2, 3]`)

In [ ]:
# Try now 
from copy import deepcopy
b = deepcopy(a)
b[1].pop()  # Removes (last) item on the list
print(a)
print(b)

### 9.2 Error handling

Sometimes there problems come up in the code that make it not function properlu. When that happens, if there is no error raised, the problem could be anywhere and that makes it very hard to fix.

Setting up informative *errors* if something is not working well, on the other hand, tells us where things go wrong and point us to what we need to fix.

In [ ]:
# Errors in Python are called Exceptions. 
e = Exception()
type(e)

In [ ]:
# Exceptions are raised with the "raise" keyword: 
raise Exception('Oops!')

Every *part* of your program, for example each function, must be in charge of things going as expected inside its body. If something goes wrong, it should tell us what happened.

One way to do this is to check for possible problems before they occur:

In [ ]:
def age_a_person(person):
    if not hasattr(person, 'age'):
       raise Exception(f'The person must have an age attribute! Given: {person}')
    return person.age + 1

age_a_person('notaperson')

Python encourages that one should first try, and *catch* any expected errors that occur, handling them then. By *catching an error* we mean the following:


In [ ]:
def age_a_person(person):
    try:
        return person.age + 1
    except AttributeError as e:
        raise Exception(f'The person must have an age attribute! Given: {person}') from e

age_a_person('notaperson')

### 9.3 Default values in functions

In `python` we get to assign default values to inputs of functions. For example:

In [17]:
# New function "f"
def f(a = 1, b = 2):
    return a + b


In [ ]:
# Function "f" can be validly be called in the following ways
print(f())
print(f(10))
print(f(b = 4))
print(f(10, 4))
print(f(a = 10, b = 4))
print(f(b = 4, a = 10))

In [ ]:
# But NOT like this
f(a = 10, 4)

---
## 10. Particular topics

* Dates, web scrapping, intro to text mining