# SESSION B1: R (i)

By **Miquel Torrens i Dinarès**

*Barcelona School of Economics*

*Data Science Center*

January 4, 2022

## 1. The R Environment

* Complete user manual: https://cran.r-project.org/doc/manuals/r-release/R-lang.html.
* As a beginner, I recommend to start with [RStudio](https://www.rstudio.com/).
* As you gain experience and deal with more demanding projects, you can execute your scripts on the [R-GUI console](https://cran.r-project.org/) (current release: `R 4.1.2`), or directly in the Terminal

### 1.1 Introduction

When you open an `R` session, a **console** is displayed, which is where all operations in `R` are run. This is built on an `R` environment that we will call **workspace**. This is the playing field that will contain everything needed to run your code.

In a nutshell, in an `R` workspace there are *things* (objects) and *actions* (operators and functions). Objects are located inside the workspace, and we apply functions to these objects to obtain some desired output. For example: we can create a vector `x` (object) and compute its `mean` (function)


In [ ]:
x <- 0:10  # This defines a numeric vector "x" with integers from 0 to 10
mean(x)  # This computes the mean of the vector

[1] 5

Here we displayed an object, an operator, and a function. To create an object, we used an operator of assignment `<-` (right-to-left), and we called a function on this object by placing it inside brackets. We also showed how to comment your code: use `#` to let `R` know it should not run the rest of the line.

Some functions do not require an object to be called. For example, you can explore the objects in your workspace using


In [ ]:
ls()

Most functions also admit **arguments**, which are specifications to control how a function should be run.

In [ ]:
pi  # This is a special object built into R
round(pi)  # This functions rounds a number to any decimal point (by default, 0)
round(pi, digits = 1)  # The argument "digits" controls the number of decimals
round(pi, digits = 4)

You can know which arguments are admitted by each function, alongside with a detailed function description, by using the `help()` function, or by typing in an `?` in front of the name of the function:

In [ ]:
?mean

`R` has a wide array of general functions and operators embedded natively that allow you to do pretty much anything basic. Those functions not readily available that you might require for specific purposes will need to be either (a) installed and loaded from external packages, or (b) coded by YOU. Like many things, coding functions can be both fun and painful.

Similarly, you will not create all objects from scratch in a workspace, sometimes you will be importing data, either numeric, in text, or any other format (maps, JSON, SQL, etc.). Your workspace is just the place where you will work on them to generate some output of interest.

Finally, don't forget to exit your `R` session once your job is done! Do that using the quit function

In [ ]:
q()

Use the command `rm(list = ls())` instead if you don't want to leave the session but want to remove every object in it. But use it with caution!

### 1.2 General rules to programming (with `R`)

1. **Reproducibility** is everything: write your code in an `R` script (file with extension `.R`), **NOT** in the console
2. **Comment your code thoroughly** and clarify everything, someone else might read it and needs to know what's happening (even yourself in the future)
3. Follow a **style guide** and do it **consistently**: spacing, indenting, format..., just like you do writing natural language. [This one](http://adv-r.had.co.nz/Style.html) is decent, no need to follow it to the letter, it's an example that you can tweak to make it your own: just stick to the basics, stay consistent and write as if it were to be read. Remember: **clean code = happy programmer**.

## 2. Input/Output


### 2.1 Importing functions (libraries)

Libraries are bundles of functions generally related to one particular topic. For example, the `xtable` package includes a set of functions to convert a table into LaTeX readable format.

In `R`, packages need to be installed prior to its use, which then can be loaded into the workspace.

In [ ]:
# Install the required package (use single or double quotation marks)
install.packages('xtable')

# Load it into your workspace
library(xtable)  # Option 1
require(xtable)  # Option 2

Both commands do the exact same task: dump every function in the package into your workspace -- the only practical difference is that if the loaded package is not available, `library` will crash, while `require` just returns a warning.

In [ ]:
# The following command will give an error
require(mombf)
library(mombf)

There are two ways to call a function from an installed package:

In [ ]:
data1 <- matrix(1:9, ncol = 3, nrow = 3)
data2 <- xtable(data1)  # NOT recommended
data2 <- xtable::xtable(data1)  # RECOMMENDED (double colon)
print(data1)
print(data2)

I would recommend that you use **only** the essential libraries you need for your task. Since packages are generally coded by other users, they might
* change over time (affecting the time-consistency of the code)
* be more prone to errors (smaller critical mass to properly test them)
* be *sui generis* with respect to `R`'s proper code structure (susceptible to transient trends)
* cause cross-platform trouble and run into replication problems.

In summary, if you can do the same thing using only base packages (with reasonable effort), it's much safer to avoid imports in the long run; and if you use an external package, keep it simple and go for the most robust choice, and easily recognisable.

### 2.2 Importing and exporting external data

Here we detail the process of importing and exporting data into an `R` session. Some popular native functions

In [ ]:
# NOT RUN
read.csv()  # Import data from a CSV
read.txt()  # Import from TXT file
read.fwf()  # Read fixed width format files
read.table()  # General function
readLines()  # Import lines of text
download.file()  # To download a data file from a URL
# END NOT RUN

You need to supply the file path to these functions to load the data itself.

The library of functions `foreign` will help you to read a number of different other data formats. Most commercial softwares have their own reading methods. For example, to import from Excel you need the function `read_excel()` in the `readxl` package. The `haven` package contains functions to read output files from other popular dinosaur softwares such as Stata, SPSS or SAS. If you use RStudio, some of these imports are automatised in the tab *Import dataset*.


Similarly to the reading functions, there are equivalent writing functions to save your output into non-`R` generic formats: `write.csv()`,  `write.table()`, or `writeLines()`.

### 2.3 Importing and exporting R files

Sometimes you will want to save an object created in `R` to an external file. There are two natural formats to produce `R` outputs: `.RData` or `.rda` (more than one object can be stored), and `.rds` (only one object).

In [ ]:
# Write an object on an external file (.RData, rda, rds)
save(data1, file = 'data1.RData')  # .RData or .rda
saveRDS(data2, file = 'data2.rds')  # .rds
save.image(file = 'workspace.RData')  # This saves the entire workspace

Similarly, you might want to read a file produced in `R`. an `.RData`, again two ways to load them:

In [ ]:
rm(data1, data2)  # Remove objects in the workspace to prove this works
load('data1.RData')  # This loads into workspace with the name it was saved with
data2 <- readRDS('data2.rds')  # This needs an assigment
print(data1)
print(data2)

You can actually run an `R` script itself by supplying the command `source()` with the `.R` file path.

Other relevant functions:

In [ ]:
print
cat
message, warning
format
sink
flie.copy, file.create, file.remove, file.rename, dir.create
file.exists
file.info
download.file

## 3. Objects and object classes

The **class** of an object determines (a) its structure and (b) what/how functions can be applied to it. 

### 3.1 Common object classes

Here we summarise some of the most common object classes:

1. Vectors: essentially three types (but not only)

  a. `numeric` (float or double) and `integer`

  The difference is integers use no decimal points and so are less demanding in terms of memory.

  b. `character` and `factor`
  
  Factors are characters that can only take a specific set of values (known as `levels`), as in a categorical variable.

  c. `logical`
  
  Booleans, they can only be `TRUE` or `FALSE`.

2. `list`

  They allow you to have different objects (maybe of different class) in one single objects, using *slots*, having one object in each slot.

3. `data.frame`

  Rectangular data structure similar to a matrix, with rows and columns, where each column can be of a different type.
  
4. `matrix` and `array`

  Matrices are similar to data.frames but less flexible: all its elements have to be of the same classe. On the other hand, computations with matrices are more efficient. arrays are just matrices with potentially more dimensions.


In [ ]:
# Types of vectors
# [c() creates a vector: it is a function to concatenate elements]
x1 <- c(1.4, 2.3, 3.2, 4.1)  # numeric
x2 <- c(1L, 2L, 3L, 4L)  # integer
x3 <- c('A', 'B', 'C', 'A')  # character
x4 <- factor(c('A', 'B', 'C', 'A'))  # declare it as factor with levels "A", "B" and "C"
x5 <- c(TRUE, FALSE, TRUE, FALSE)  # logical

# The "class" function tells you what class an object is
class(x1)  # To obtain a boolean, try: is.numeric(x1)
class(x2)  # Try: is.integer(x2)
class(x3)  # Try: is.character(x3)
class(x4)  # Try: is.factor(x4)
class(x5)  # Try: is.logical(x5)

Some classes can be *coerced* into other classes: for example a numeric vector can be coerced into a character vector, and vice versa if the elements of the vector are digits. But numeric vectors cannot be coerced into logical. Use the functions
- `as.numeric()`,
- `as.integer()`,
- `as.character()`,
- `as.factor()`,
- `as.logical()`,

to convert objects into other classes.

If some class is not coercible into another, you may be able to use a coercible middle class to do the trick. For example, if `x` is a factor with values in 1, 2, 3, you may coerce it into numeric using

In [ ]:
x <- as.factor(c(4:6, 6:4))  # x is a factor
cat('* Class of "x":', class(x), '\n')
print(x)  # This will print the levels

# Factors are not coercible to numeric
y <- as.numeric(x)
print(y)  # WRONG result

# Use character as a translator
z <- as.numeric(as.character(x))  # factor -> character -> numeric
cat('* Class of "z":', class(z), '\n')
print(z)

As for the rest of object classes, here's how to create them:

In [ ]:
# Create a list
a <- list('a' = x, 'b' = z) # with two "slots", with names "a" and "b"
print(a)

# Create a data.frame
b <- data.frame('col1' = x, 'col2' = y, 'col3' = z)
print(b)

# Create a matrix
m <- matrix(1:12, ncol = 3)
print(m)

These classes are coercible as well, using `as.list()`, `as.data.frame()`, and `as.matrix()`, but **BE CAREFUL** in any type of class coercion, and always inspect the coerced object to make sure the result is in the correct desired format.

In more advanced levels you will encounter more classes that stem from this basic set, and more complex, such as [`S4` objects](http://adv-r.had.co.nz/S4.html). You will also learn to create your own classes.

### 3.2 Functions applicable to a class

Functions are applied to specific classes. For example, the function `mean()` can be applied to an object of class `numeric`, but applying it to an object of class `character` or `factor` would generate an error in your workspace:

In [ ]:
x1 <- c(1, 7, 4, 8, 6, 0)
x2 <- as.factor(c('a', 'c', 'd', 'b', 'b', 'd'))
print(mean(x1))  # OK
print(mean(x2))  # Can't do it

[1] 4.333333


Warning message in mean.default(x2):
“argument is not numeric or logical: returning NA”


[1] NA


(Note: characters require quotation marks, otherwise it would be as if you were creating a vector with objects `a`, `b`, `c` and `d`, which do not exist.)

Other functions are applicable to both classes, but mind you they might produce different types of output:

In [ ]:
cat('* Summary of object "x1"\n')
summary(x1)
cat('* Summary of object "x2"\n')
summary(x2)

* Summary of object "x1"


   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   1.750   5.000   4.333   6.750   8.000 

* Summary of object "x2"


a b c d 
1 2 1 2

You can find out if a function is usable on your object class with the function `methods()`, which will display all classes that a given (native) function can handle:

In [ ]:
methods(summary)

### 3.2 Quick object inspection

Sometimes we have an object of a given class that you want to inspect.

In [ ]:
set.seed(666)  # This functions "controls" the random
x <- rnorm(10000, mean = 0, sd = 1)  # 10K random values from a standard normal
y <- list(A = 1:100, B = letters[1:22], C = rnorm(10), D = c(TRUE, TRUE, FALSE))
z <- data.frame(col1 = 1:100, col2 = 101:200, col3 = 201:300)
w <- as.matrix(z)

cat('* Structure of object "x"\n')
str(x)  # This functions provides the structure of the object
cat('* Structure of object "y"\n')
str(y)
cat('* Structure of object "z"\n')
str(z)

The function `summary` above applies to most classes, and some other quick-look functions are also useful.

In [ ]:
x <- round(x, 4)  # For display purposes

head(x)  # Provide first values
head(x, n = 10)
tail(x)  # Provide last values
x[1]
x[7287]  # Provide value no. 7,287
x[10001]  # Returns NA: element 10K+1 doesn't exist

Note that indexing in `R` is as in natural language: it starts at `1` (Python is at `0`).


Different classes have different attributes that can be inspected:


In [ ]:
# Matrices and data.frames have dimensions and they have names
dim(z)  # Dimension
nrow(z)  # No. of rows
ncol(z)  # No. of columns
colnames(z)  # Names of the columns
head(rownames(z))  # Names of the rows
rownames(z) <- paste('row', 1:nrow(z), sep = '')  # All these can be changed
head(rownames(z))

# Lists can also have names but no dimension (they have length)
names(y)
length(y)

# So do vectors
names(x)  # This vector has no names, but they can be assigned
length(x)
names(x) <- paste('val', 1:length(x), sep = '')
head(names(x))

# For non-continuous vectors, this is a really useful function
v <- c('A', 'B', 'A', 'C', 'C', 'A', 'A', 'B', 'C')
table(v)  # Absolute frequencies

and different operators to access its elements

In [ ]:
# Vectors: single parenthesis (access either by index or by name)
x[1]
x['val1']  # same
x[-1]  # negative indices used to drop elements: all elements except the first
x[-(1:5)]  # return every element except those in 1 to 5
x[11:20][7]  # you can "double" subsets: return element 7 from the set 11 to 20

# Lists: double parenthesis (index or name)
y[[1]]  # First element of the list is a vector
y[[1]] <- y[[1]][1:10]  # Lets shorten it: keep first ten values (reassignment)
y[[1]]  # Repeat: now shorter vector
y[['A']]  # same result
y$A  # same, but NOT recommended: "partial matching" can cause errors

# Why not use the "$" operator? Let's see what can happen
names(y) <- c('Abcd', 'Defg', 'Hijk', 'Lmno')  # Let's set new names
y[['A']]  # NA (well-done!): a slot named "A" does not exist
y$A  # Returns an element, WRONG: I call for 'A' and it gives me something with a different name

# data.frames and matrices: ROWS before *comma*, COLUMNS after
head(z[, 1])  # column 1
head(z[1, ])  # row 1
head(z[1, 1])  # element 1 in column 1
head(z[, 'col1'])
head(z['row1', ])

# Operator "$" works also for data.frames, but not for matrices
head(z$col1)  # In data.frame: NOT recommended
try(head(w$col1))  # In matrix: ERROR

colnames(z) <- c('Abcd', 'Defg', 'Hijk')  # Same exercise: partial matching
head(z[, 'A'])  # ERROR: good!
head(z$A)  # Again: it gives you something you're not asking for

Generally, avoid the use of the `$` operator: it's shorter code but more prone to errors (code of lower quality and robustness), especially in lists and `data.frame`'s. Instead, use either indexing or (if named) full quotation.

## 4. Operators

Operators are functions in the form of symbols to perform specific mathematical or logical computations. We provide a list of the native `R` operators with an example:

### 4.1 Basic operators

*   **Arithmetic** operators

In [ ]:
# Numeric and integer vectors
3 + 1  # addition
3 - 1  # subtraction
5 * 2  # multiplication
5 / 2  # division
5 %% 2  # remainder
5 %/% 2  # quotient
2 ** 3  # exponentiation, also: 2^3
exp(1)  # e^1 = 2.718282... (NOT an operator)

# Matrix operators
A <- matrix(1:9, ncol = 3)
B <- matrix(10:18, ncol = 3)
A * B  # elementwise multiplication (!)
A %*% B  # matrix multiplication
A %o% B  # outer product

[1] 4

[1] 2

[1] 10

[1] 2.5

[1] 1

[1] 2

[1] 8

[1] 2.718282

[,1] [,2] [,3]
[1,] 10   52   112 
[2,] 22   70   136 
[3,] 36   90   162

[,1] [,2] [,3]
[1,] 138  174  210 
[2,] 171  216  261 
[3,] 204  258  312

, , 1, 1

     [,1] [,2] [,3]
[1,]   10   40   70
[2,]   20   50   80
[3,]   30   60   90

, , 2, 1

     [,1] [,2] [,3]
[1,]   11   44   77
[2,]   22   55   88
[3,]   33   66   99

, , 3, 1

     [,1] [,2] [,3]
[1,]   12   48   84
[2,]   24   60   96
[3,]   36   72  108

, , 1, 2

     [,1] [,2] [,3]
[1,]   13   52   91
[2,]   26   65  104
[3,]   39   78  117

, , 2, 2

     [,1] [,2] [,3]
[1,]   14   56   98
[2,]   28   70  112
[3,]   42   84  126

, , 3, 2

     [,1] [,2] [,3]
[1,]   15   60  105
[2,]   30   75  120
[3,]   45   90  135

, , 1, 3

     [,1] [,2] [,3]
[1,]   16   64  112
[2,]   32   80  128
[3,]   48   96  144

, , 2, 3

     [,1] [,2] [,3]
[1,]   17   68  119
[2,]   34   85  136
[3,]   51  102  153

, , 3, 3

     [,1] [,2] [,3]
[1,]   18   72  126
[2,]   36   90  144
[3,]   54  108  162

*   **Relational** operators (returning a boolean)

In [ ]:
7 > 2  # bigger than
7 < 2  # smaller than
7 >= 2  # bigger or equal than
7 <= 2  # smaller or equal than
7 == 2  # equal to
7 != 2  # different than

*   **Logical** operators (test if a statement is true)

In [ ]:
(7 > 2) & (3 > 4)  # AND
(7 > 2) | (3 > 4)  # OR
! (7 > 2)  # NOT
xor(7 > 2, 3 > 4)  # AND/OR (not an operator)

If the elements to which we apply a logical operator are vectors (of the same length), the operator will return a logical vector comparing the two input vectors elementwise: you can use double `AND` or `OR` to inspect only the first element: `x && y`, or `x || y`.

*   **Miscellaneous** operators

In [ ]:
2:8  # Integer sequence of 2 to 8
7 %in% 2:8  # Is an element inside of a vector

Some other basic operators are already covered in other sections, like the help operator (`?`), component/slot extraction (`$` and `@`), indexing (`[` and `[[`), formula (`~`) and library access (`::` or `:::`).

*   **Assignment** operators: we cover them in the next subsection.

Like in every language, operators in `R` have *precedence*, i.e. in the same expression some operators are applied before others. Think of math: in an equation we multiply before we add, thus in the expression `x <- 1 + 3 * 4` gives 13 instead of 16, i.e. `*` has precedence over `+`. There is a precedence order for all operators in `R`: explore the precedence list using the command `?Syntax`.

### 4.2 Assignment

In `R`, objects can be created, re-written and removed without restrictions. Once an object is declared, the expression we are assigning to it is evaluated. The standard method of assigment is the use of the operator `<-`, even though there are other options. We illustrate the most common ones:

In [ ]:
# Vector
rm(x)  # Remove the object from the workspace
x <- c(1, 7, 4, 8, 6, 0)

# Here the expression "mean(x)" will be evaluated 4 times
x1 <- mean(x)  # Good :-)
x2 = mean(x)  # NOT good: "=" is *not* an assigment operator
x3 <<- mean(x)  # Used only in functions to declare an object in a superior environment
assign('x4', mean(x))  # Good: useful when the object has an "unknown" name
mean(x) -> x5  # Good, but standard is to assign right to left (same with ->>)

# Test if the four objects were assigned correctly
identical(x1, x2, x3, x4, x5)  # It returns TRUE if the objects are equal

For more advanced assignment methods, I recommend you also check the functions `get()`, `with()`, and `within()`.

Multiple assignments require multiple operators:

In [ ]:
obj1 <- obj2 <- 1:5
#obj1, obj2 <- 1:5  # NOT POSSIBLE

ERROR: ignored

**(!) NOTE** – Although technically you can assign an expression using the `=` symbol, `=` is not formally an assignment operator in `R`, and its use is designed for functions. That's why it is **not** recommended despite widespread misuse. In short, refrain from assignment use.

### 4.3 Reserved words

There are certain reserved words in `R` (keywords) that cannot be assigned or over-written since they are essential built-in elements. We list the most important, words for:

*   Booleans: `TRUE`, `FALSE`.
*   Iterables: `if`, `else` (`if`-statements), `for`, `in`, `next` (`for`-loops), `while`, `break`, `repeat` (`while`-loops).
*   Functions: `function`, `...`.
*   Particular values: `NA`, `NULL`, `NaN`, `Inf`.

We review most of them later on.

Still, even if the rest functions in `R` can be over-written (stuff like `mean <- 3` is factually perpetrable), refrain from doing it.

## 5. Functions

Functions are often used to encapsulate a sequence of expressions that need to be executed numerous times, with some explicitly specified set of parameters or *arguments* that give it flexibility. Functions are stored in the `R` environment like any other object, in this case with class `function`.

### 5.1 Coding functions

Coding functions in `R` is fairly simple. You only need three basic things: the `function` function, the list of inputs (if any) it requires, and the `return` function to output your desired object (if any). 

In [6]:
# Define function to compute the mean of numeric vector
average <- function(x) {  # input "arguments" inside parenthesis,
  n <- length(x)          # commands of the function inside "{" and "}"
  avg <- sum(x) / n
  return(avg)  # "return" assigns the outcome to "average"
}

# Function to compute the mode
the.mode <- function(x, print.it = TRUE) {  # Some arguments can have a default value
  freqs <- sort(table(x), decreasing = TRUE)  # Nested function
  value <- names(freqs)[1]
  if (print.it == TRUE) {
    cat('The mode is:', value, '\n')
  }
  return(value)
}

# You can create a function calling to other functions of yours
mean.and.mode <- function(x, y) {  # Multiple arguments
  obj1 <- average(x)
  obj2 <- the.mode(y)
  return(c(obj1, obj2))
}

# Arguments and outputs are not even mandatory for a function
hello.world <- function() {  # Keep the parenthesis though!
  cat('Hello world! My coding teacher is awesome.\n')
}

avg1 <- mean(1:10)
avg2 <- average(1:10)  # Here you call your first function
identical(avg1, avg2)  # They should be the same
mode1 <- the.mode(c(2, 2, 3, 4, 4, 4, 1))
mode2 <- the.mode(c(2, 2, 3, 4, 4, 4, 1), print.it = FALSE)  # change default
mode3 <- the.mode(c('A', 'D', 'B', 'B', 'C'))
mode3
mean.and.mode(1:10, c(2, 2, 3, 4, 4, 4, 1))  # Assigning is not mandatory
hello.world()

[1] TRUE

The mode is: 4 
The mode is: B 


[1] "B"

The mode is: 4 


[1] "5.5" "4"

Hello world! My coding teacher is awesome.


$x



By default, if no `return()` function is used, a function will return the last expression evaluated (although this is not recommended praxis).

**Important: what happens in a function stays in the function.** Keep in mind that functions have their own *environment*: everything inside `{` and `}` occurs on a separate environment *inferior* to the global one. This means that once you're **inside** the function, what exists in the "superior" environment (the workspace you're in) is known, but the objects created therein live in that separate space and are not poured onto the superior global environment, unless you explicitely tell them to (as one does using `return`).

### 5.2 The `apply` family of functions

Sometimes you will encounter situations in which you want to apply a function repeatedly to elements of an object without using expensive loops. The set of `apply` functions are efficient and elegant ways to do that. There are more `apply`-type of functions, but here we present the four more common ones

*   `apply`: used to iterate over the dimensions of a `data.frame` or `matrix` or larger `array`-type objects, the simplest case being to apply a function on each row/column
*   `lapply`: uses `apply` on `list`-type objects, and also outputs a `list`
*   `tapply`: summarises a vector by groups defined by another vector, i.e. say you want the group-mean of variable `x`, where in one column you have the value of `x` and the group they belong to in another
*   `sapply`: uses `apply` on vector-type objects, returning a vector

Check out other functions like `vapply` (similar to `sapply`), `mapply` (for multiple parallel data structures), `mcapply` (multi-core), `mclapply` (multi-core `lapply` from the `parallel` package).


In [23]:
df1 <- data.frame(x = 1:10, y = 11:20, z = -10:-1)
df2 <- data.frame(x = 1:10, group = c(rep('A', 5), rep('B', 5)))
df3 <- data.frame(x = c('a', 'b', 'c', 'a'), y = c('e', 'e', 'f', 'f'))
l1 <- list(A = 1:10, B = 11:20, C = -10:-1)

# On the columns of df: find the max of each
apply(df1, 2, max)  # "2" is the dimension: in this case is columns (1 = rows)
                    # order of arguments: object, dimension, function to apply

# Same operation but now the vectors are elements of a list
lapply(l1, max)  # output object is a list (here you need no dimension)

# Compute the mean of "x" as a function of "group"
tapply(df2[, 'x'], df2[, 'group'], mean)

# Similar to "apply" but directly on a set of vectors
sapply(df1, class)

# Check how many unique elements are in each column
apply(df3, 2, function(x) { length(unique(x)) })  # This is an "anonymous" function! It is never defined

x  y  z 
10 20 -1

$A
[1] 10

$B
[1] 20

$C
[1] -1

A B 
3 8

A  B  C 
10 20 -1

x         y         z 
"integer" "integer" "integer"

x y 
3 2

The `apply` family of functions are formally *functionals*: functions that take another function as an argument. They are very important and frequently used in `R`, and can become quite complex quickly. I recommend the following link to Hadley Wickham's book if you wish to go deeper on the set of `apply` functions: http://adv-r.had.co.nz/Functionals.html.

### 5.3 Useful miscellaneous functions

In [ ]:
args(median)
formals(median)
body(median)

try()
debug()
stop()
warning()

unlist()

sort
seq
nchar

unique

## 6. Dataset manipulation: subsetting and merging

Often times you want to clean, select, merge and, in a nutshell, manipulate datasets. Here we present basic operations that allow us to perform these tasks. We had a preview in Section 3.2. on how to select elements on different classes of objects, but here we concentrate on common relational datasets, such as `data.frame`'s and matrices.

### 6.1 Subset and expand

We start covering the operations to subset or expand a dataset.

In [7]:
set.seed(666)  # This function "controls random", i.e. we all get the same random numbers
df <- data.frame(x = 1:10, y = rep(c('A', 'B'), 5), z = rnorm(10))

# Select a set of observations (KEY: position of the comma)
df1 <- df[which(df[, 'x'] > 6), ]  # Select observations where variable x > 6
df2 <- df[which(df[, 'x'] > 6 & df[, 'y'] == 'A'), ]  # Double condition

# Select a set of columns (KEY: position of the comma)
df3 <- df[, which(colnames(df) != 'x')]  # Select every column except "x": this is more robust than "df[, -1]" 
df3 <- df[, which(colnames(df) %in% c('A', 'B'))]  # Identical with %in% operator

# Order the observations by the value of a row, or column
df4 <- df[order(df[, 'z'], decreasing = TRUE), ]  # Order rows by value of column "z" (highest-to-lowest)
df5 <- df[, c('z', 'y', 'x')]  # Change order of columns

# Add columns or rows
df6 <- cbind.data.frame(df5, w = 11:20) # cbind for matrix
df6[, 'v'] <- 21:30  # add a new column from a new object
df7 <- rbind.data.frame(df5[1:5, ], df5[6:10, ]) # rbind for matrix
df7[11, ] <- c(11, 'B', 0)  # add a new observation from a new object

# Rename variables or observations, change class, transform
colnames(df5) <- c('Z', 'Y', 'X')
rownames(df5) <- paste('obs', 1:nrow(df5), sep = '')
df5[, 'X'] <- as.integer(df5[, 'X'])  # it's ok to re-write: it is reversible
df5[, 'Z'] <- df5[, 'Z'] * 3  # modify an existing column
colnames(df5)
rownames(df5)

[1] "Z" "Y" "X"

[1] "obs1"  "obs2"  "obs3"  "obs4"  "obs5"  "obs6"  "obs7"  "obs8"  "obs9" 
[10] "obs10"

Some thoughts on these operations:

*   The function `which()` is one you should get acquainted with very well. It depicts the elements of a set *which* satisfy the logical condition(s) in parenthesis.
*   Be aware of the distinction between `sort()` and `order()`: the former grabs a set of values and puts them from lowest to highest, the latter gives you the indices in the vector of said order, not the values themselves.
*   One helpful function we have not looked into is `subset()`, which essentially does the same thing we did above. It works well for simple commands, but the framework above is more flexible and can deal with complex operations. Feel free to use it though! Try: `subset(airquality, Temp > 80, select = c(Ozone, Temp))`.
*   Notice I never modify the original object I am subsetting. It is important that when you subset that you don't over-write previously existing objects (and, in particular, the object you are subsetting), unless you recursively subset one particular object. These operations are **irreversible**, in the sense that if you over-write the object being subsetted, the information that was cut out cannot be re-used anywhere else in your code. Often times this is not desirable. If you have memory problems in your CPU, you have to balance this with keeping as few possible copies of the data as possible, but try to keep the originals intact in your workspace.

### 6.2. Merge and join

Beyond the straightforward expansion or selection of rows and columns explained before, one may want to *merge* two datasets, e.g. we have different data on the same set of individuals, or different years, etc. This usually involves joining two full datasets, instead of just adding rows or columns based on some coditions.

In [6]:
set.seed(666)
df1 <- data.frame(id1 = sample(1:10, replace = FALSE), col1 = rnorm(10), col2 = rchisq(10, df = 1))
df2 <- data.frame(id2 = sample(1:10, replace = FALSE), col3 = rnorm(10), col4 = rchisq(10, df = 1))
head(df1, 5)
head(df2, 5)

# Joint datasets using "match"
df3 <- cbind.data.frame(df1, df2[match(df1[, 'id1'], df2[, 'id2']), -1])  # Exclude "id" column to avoid redundancy
head(df3, 5)

# Joint datasets using "merge"
colnames(df1)[1] <- 'id'
colnames(df2)[1] <- 'id'
df3 <- merge(df1, df2, by = 'id')  # This is fine but be careful if ID lists and column names are not equal
head(df3, 5)  # The original order is altered

id1 col1        col2     
1 5    1.23528305 3.0634462
2 9   -0.08365711 0.8760082
3 4    0.25683143 2.8367350
4 1   -1.07362365 0.3991052
5 2   -0.62286788 1.5607040

id2 col3       col4     
1  1  -0.9564482 0.1428781
2  8   1.1390113 1.5188775
3 10  -1.4151442 0.1644284
4  6   0.2009336 0.4742982
5  7  -1.2343732 0.1326316

id1 col1        col2      col3       col4     
8 5    1.23528305 3.0634462 -0.3334186 0.3311042
6 9   -0.08365711 0.8760082 -0.1211411 0.9001866
7 4    0.25683143 2.8367350  0.6722846 2.3237402

id col1       col2      col3       col4     
1 1  -1.0736237 0.3991052 -0.9564482 0.1428781
2 2  -0.6228679 1.5607040  2.3682631 0.3960097
3 3   0.2849911 1.3178794  0.2514136 0.6331147

The function `match()` basically looks for the elements of the first vector present in the second vector, and returns the corresponding indices of the latter in the order of the former. It is another hall-of-famer function in `R` and is super useful in a number of contexts. Use it!

Using `merge()` is also a good option, especially if you're familiar with classic database management, as it is well equipped to easily do *inner* (default), *outer* (left, right) and *cross* joints.

## 7. Control flows

We cover `if` statements, and the basic loops: `for`, `while`, `repeat`.

### 7.1 `if`-statements

When you want to run some chunk of code only if a certain condition hold (and maybe some other chunk if it doesn't, we use `if`-clauses.

In [6]:
gender <- 'male'
age <- 20 

# If-statement: use logical object as condition, then indent conditional actions
# Isolate condition in parenthesis, with pre- and post- single space
cat('* Person: ')
if (gender == 'female') {  # "if" clauses use "{" and "}"
  if (age > 18) {
    cat('Woman.\n')
  } else {
    cat('Girl.\n')
  }
} else if (gender == 'male') {  # "else if" tell what happens if there is another mutually exclusive condition
  if (age > 18) {
    cat('Man.\n')
  } else {
    cat('Boy.\n')
  }
} else {  # "else" tell what happens if previous conditions do not hold
  cat('Other gender.\n')
}

# Other ways to use if-statements
if (gender == 'male') cat('* Gender is male.\n')  # You can skip the clause if single-line (not recommended)
under.age <- ifelse(age < 18, 'Yes.', 'No.')  # Assign first element if condition holds, second element otherwise (single element operation)
cat('* Is the person under age:', under.age, '\n')

* Person: Man.
* Gender is male.
* Is the person under age: No. 


Note that `if`-conditions do not require an `else` statement, this is used when something in the code must happen either-or. If you only want a part of the code to run (without `else` contingency), you can just write `if (...) { ... }` and omit the rest.

### 7.2 `for`-loops

These are used when you want to apply a set of operations on an *iterable* object. A `for`-loop will replicate the computations for each element of the $n$ elements of the object and provide $n$ results.

In [11]:
n <- 5  # 5 elements
x <- rep(NA, n)  # Set an empty vector with n elements
for (i in 1:(2 * n)) {  # For element "i" from 1:n, perform the following operations
  cat('Iteration:', i, '\n')
  result <- i^2 - 5  
  if (result < 0) {
    next  # This is necessary because later I compute the squared root
  }
  x[i] <- sqrt(result)  # Set the i-th element with the squared root
  if (i > n) {
    break  # I only have n elements in the vector, the n+1 could not be assigned
  }
}

# Check the outcome
print(x)

Iteration: 1 
Iteration: 2 
Iteration: 3 
Iteration: 4 
Iteration: 5 
Iteration: 6 
[1]       NA       NA 2.000000 3.316625 4.472136 5.567764


The set of operations can be of any difficulty and length, this is just regular code: the only difference is that you repeat them for each element on the list

**Note:** there are two critical *reserved* words when looping: `next` and `break`. These are used to prevent loops from getting stuck or running into errors.

*   `next`: this will make a loop jump immediately to the next iteration, without running the remaining body of the loop from that point on (on the current iteration)
*   `break`: it will make the loop stop completely, i.e. you exit the body of the loop and proceed with the rest of the code normally.



### 7.3 `while`-loops (and `repeat`)

These are used when you want an iterable loop to be executed as long as a certain condition holds. It is structured like a `for`-loop, but they as an `if`-statement: testing a condition. This condition is tested every time the body loop is executed, until it does not hold.

In [5]:
count <- 0
while (count < 10) {
  count <- count + 1
  cat('* Count:', count, '\n')
}

# "repeat" works in the same way but needs a "break" to stop
count <- 0
repeat {
  count <- count + 1
  cat('* Count:', count, '\n')
  if (count == 10) {
    break
  }
}

* Count: 1 
* Count: 2 
* Count: 3 
* Count: 4 
* Count: 5 
* Count: 6 
* Count: 7 
* Count: 8 
* Count: 9 
* Count: 10 
* Count: 1 
* Count: 2 
* Count: 3 
* Count: 4 
* Count: 5 
* Count: 6 
* Count: 7 
* Count: 8 
* Count: 9 
* Count: 10 


## 8. Stats and math

### 8.1 Basic functions

One of `R`'s strongest suits is the amount of statistical software it is fluent in, whether natively or with packages that run on it. Here we provide the very basics to get you started, and introducte some of the functions that are bread and butter for statistical and mathematical programmers.

In [9]:
# Basic mathematical functions (operators aside)
abs(-3)
sign(c(-4, 0, 7))
exp(3)
log(100); log10(100); log2(64)  # Note you can separate commands with ";"
sqrt(25)
sin(1); cos(1); tan(1)
choose(5, 3)  # Combinatorial number (n choose k)
factorial(5)  # Factorial number: x!
combn(1:4, 2)  # Provides all combinations of "2" elements in the set 1:4

# Basic statistical summaries
x <- seq(-3, 3, 1)
y <- seq(-6, 6, 2)
max(x)  # Cumulative maximum: cummax(x)
min(x)  # cummin(x)
sum(x)  # cumsum(x)
prod(x)  # cumprod(x)
diff(x)  # With respect to previous value in the vector
table(x)  # Abs. Frequencies
table(x, y)  # Contingency table
quantile(1:200, probs = c(0.1, 0.5, 0.9))
range(x)
rank(x)

mean(x)
median(x)
cor(x, y)
cov(x, y)
sd(x)
var(x)

[1] 3

[1] -1  0  1

[1] 20.08554

[1] 4.60517

[1] 2

[1] 6

[1] 5

[1] 0.841471

[1] 0.5403023

[1] 1.557408

[1] 3

[1] -3

[1] 0

[1] 0

[1] 1 1 1 1 1 1

x
-3 -2 -1  0  1  2  3 
 1  1  1  1  1  1  1 

    y
x    -6 -4 -2 0 2 4 6
  -3  1  0  0 0 0 0 0
  -2  0  1  0 0 0 0 0
  -1  0  0  1 0 0 0 0
  0   0  0  0 1 0 0 0
  1   0  0  0 0 1 0 0
  2   0  0  0 0 0 1 0
  3   0  0  0 0 0 0 1

10%   50%   90% 
 20.9 100.5 180.1

[1] -3  3

[1] 1 2 3 4 5 6 7

[1] 0

[1] 0

[1] 1

[1] 2.160247

[1] 4.666667

We will list, however, some useful and verycommon matrix algebra functions (to use on `matrix`-type objects):

*   `t` (matrix transpose), `diag` (matrix diagonal)
*   `crossprod`, `tcrossprod`, `outer` (cross-, transpose-cross- and outer-products)
*   `eigen`, `qr`, `svd` (eigen, QR and SVD decompositions)
*   `rcond` (condition number)
*   `solve` (matrix inverse, or systems of equations)

### 8.2 Statistical distributions (characterisation and simulation)

One of `R`'s strengthts is simulation power. You can find PDFs and CDFs for a wide variety of parametric distributions, as well as take random samples from them. Here are some basics to simulate things in `R`:

In [15]:
set.seed(666)
sample(1:10, 1)  # Most basic simulation function: sample 1 element out of 1:10
sample(1:5, 3, replace = TRUE)  # Replace TRUE puts the sampled values back in the pool
sample(1:5, 3, replace = FALSE)  # Once a value is drawn, it cannot be drawn again

[1] 5

[1] 1 4 1

[1] 2 3 1

There are four key letters to deal with a given available parametric distribution:

*   `d`: provides the *density* (PDF) of the distribution at the supplied value 
*   `p`: provides the *cumulative probability* (CDF) up to the supplied value
*   `q`: provides the *quantile* of the distribution that accumulates the supplied percentage of the probability mass 
*   `r`: provides a *random* sample of the supplied size for the specified distribution

We illustrate this with the Normal distribution:

In [25]:
x <- 1  # Any value on the real line
a <- 0.6  # Any value between 0 and 1
n <- 1e3  # Any integer (note the scientific notation: 10^3 = 1,000)

dnorm(x, mean = 0, sd = 1)  # PDF of the Normal at x = 1 (density)
pnorm(x, mean = 0, sd = 1)  # CDF of the Normal: returns P(X < 1)
qnorm(a, mean = 0, sd = 1)  # Quantile: returns x such that P(X < x) = 0.6
pnorm(x, mean = 0, sd = 1, lower.tail = FALSE)  # Upper-tail CDF of the Normal: returns P(X > 1)
qnorm(a, mean = 0, sd = 1, lower.tail = FALSE)  # Quantile, but opposite tail P(X > x) = 0.6, i.e. P(X < x) = 1 - 0.6
head(rnorm(n, mean = 0, sd = 1))  # Here we ask for 1,000 random draws of a N(0, 1): note we require a different parameter!

[1] 0.2419707

[1] 0.8413447

[1] 0.2533471

[1] 0.1586553

[1] -0.2533471

[1] -1.1618627 -0.9575398  0.7408697 -1.1961989  0.2315603 -1.3518877


Every distribution will have its set of parameters: the Normal here has `mean` and `sd`, which you can specify to whatever values you need, and if not specificied are taken to be `mean = 0`, and `sd = 1` (the standard Normal). But for example the `chisq` ($χ_{\nu}^{2}$) requires the parameter `df` (degrees of freedom, $\nu$), with no default, or the binomial needs to be supplied `size` ($p$) and `prob` ($k$). 

Here I list the most common distributions available and their command name: `beta`, `binom`, `cauchy`, `chisq`, `exp`, `f`, `gamma`, `geom`, `hyper`, `lnorm` (log-normal), `logis`, `multinom`, `nbinom` (negative binomial), `norm`, `pois`, `t`, `unif`, `weibull`, `wilcox`, `birthday`, `tukey`.

There are also various statistical tests that are readily available, even a summary is beyond the scope of this intro course. This set of tests is close to uncountable, so as a basic rule, if you look for "R [name of the test]" in your favourite search engine, you will most likely find what command you need quickly, for example you can do an ANOVA test with the command `anova` (surprise?).

### 8.3 Statistical models

As a final note, `R` is equipped with numerous statistical models that can be run, here I show how to run linear regression

In [44]:
# Simulate some data
set.seed(666)
n <- 100  # rows
p <- 50  # columns
X <- matrix(rnorm(n * p), nrow = n, ncol = p)  # Regression matrix
b <- c(1, 1, 1/2, 1/2, rep(0, p - 4))  # Regression coefficients
y <- X %*% b + rnorm(n)  # Model: y = X * b + epsilon, epsilon is N(0, 1)
df <- cbind.data.frame(y, X)  # Put all the data into one data.frame
colnames(df) <- c('y', paste('var', 1:p, sep = ''))  # Column names

# Linear regression
model <- lm(y ~ var1 + var2, data = df)  # "lm" is linear model: you declare a "formula" with the "~" symbol,
                                         # and add variables (names) with "+"
model <- lm(y ~ ., data = df)  # The dot tells it to add all variables

# Some useful diagnostics
# These following functions are generic: they work for most models in R!
summary(model)  # This gives you the classical table with the results
head(coef(model))  # Estimated coefficients (beta hat)
head(confint(model))  # Confidence intervals for the coefficients (you can change significance)
head(fitted(model))  # Fitted values
head(resid(model))  # Model residuals

# Prediction (create five new observations and use the estimated model to predict)
new.df <- matrix(rnorm(5 * p), nrow = 5, ncol = p) # "predict" function requires a data.frame
colnames(new.df) <- colnames(df)[-1]  # Needs to be in the same format
predict(model, newdata = as.data.frame(new.df))  # Prediction for a new observation with covariates rnorm(n)


Call:
lm(formula = y ~ ., data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.85209 -0.44267  0.03548  0.45171  1.60441 

Coefficients:
              Estimate Std. Error t value Pr(>|t|)    
(Intercept) -0.0972054  0.1293670  -0.751  0.45601    
var1         0.8675616  0.1221973   7.100 4.65e-09 ***
var2         1.0101160  0.1229673   8.215 8.99e-11 ***
var3         0.7222472  0.1373306   5.259 3.16e-06 ***
var4         0.5443718  0.1368960   3.977  0.00023 ***
var5        -0.1920666  0.1507418  -1.274  0.20862    
var6        -0.1268034  0.1636196  -0.775  0.44207    
var7        -0.0859963  0.1222497  -0.703  0.48511    
var8         0.0671576  0.1630104   0.412  0.68215    
var9        -0.1211380  0.1301038  -0.931  0.35637    
var10       -0.0020973  0.1297702  -0.016  0.98717    
var11        0.1749164  0.1438082   1.216  0.22969    
var12       -0.0526155  0.1462959  -0.360  0.72065    
var13        0.2009111  0.1343164   1.496  0.14112    
var14       -0.273

(Intercept)        var1        var2        var3        var4        var5 
-0.09720536  0.86756164  1.01011598  0.72224716  0.54437178 -0.19206660

2.5 %      97.5 %   
(Intercept) -0.3571781 0.1627674
var1         0.6219970 1.1131262
var2         0.7630040 1.2572280
var3         0.4462710 0.9982233
var4         0.2692690 0.8194746
var5        -0.4949935 0.1108603

1           2           3           4           5           6 
 0.42735670  0.98253188 -0.08173233  4.92210505 -3.13904850  0.32190933

1           2           3           4           5           6 
-0.50505047  0.39327450  0.17637673 -0.96308610  0.08577684  0.25467706

1         2         3         4         5 
 1.798792 -2.402820 -1.889108 -1.281219  1.456660

 If your outcome is binary, for example, use `glm(..., link = 'binomial')` instead as the modelling function (the rest stays the same). Many models are natively built into `R`, but many others are not. This is where packages kick in: if you're trying to estimate a model that is not built-in, most likely it has been used before and someone has written a package on it. Use the search engine rule again and you may find a solution!

## 9. String manipulation

* grep, grepl, agrep, substr, gsub
* Regular expressions


## 10. Basic data visualization

## 11. Popular packages

* data.table/dplyr/ggplot/shiny

## 12. Relevant topics

* Dates, web scrapping, visualization?