<img src = "https://github.com/barcelonagse-datascience/academic_files/raw/master/bgsedsc_0.jpg">

# Practice with R

This is a short list of short challenges to practice

In [94]:
if (!require("dplyr")) install.packages("dplyr")
if (!require("tidyr")) install.packages("tidyr")
if (!require("data.table")) install.packages("data.table")
library(dplyr)
library(tidyr)
library(data.table)

Loading required package: tidyr

Warning message:
"package 'tidyr' was built under R version 3.6.3"


### Vectors

In [2]:
# Challenge 1: Create a vector with a sequence of number from 1 to 10.
mylist<-c(1,2,3,4,5,6,7,8,9,10)
#or 
#mylist<-seq(1, 10)
#mylist<-1:10
mylist

[1]  1  2  3  4  5  6  7  8  9 10

In [3]:
# Challenge 2: From previous one,  set the 2nd and 6th elements to 'no value'
mylist[2]<- mylist[6]<-NA

mylist

[1]  1 NA  3  4  5 NA  7  8  9 10

In [4]:
# Challenge 3: From previous one,  print last 3 elements of the list
mylist[(length(mylist)-2):length(mylist)]

[1]  8  9 10

In [5]:
# Challenge 4: From 2, sum all the elements that are different than None
# Hint: do it first with a for loop
# then as alternative, try the same with sum(), managing the NA 

mysum<-0
for (i in mylist){
    if (!is.na(i)){
        mysum<-mysum+i
    }
}
mysum

# or
sum(mylist, na.rm=T)


[1] 47

[1] 47

## Matrices



In [6]:
# Challenge 1: Create two matrix 
# one 3x6 using random numbers from normal distribution 
# the other 6x4 using random numbers from uniform distribution
# and multiply them using matrix algrebra
m <- matrix(rnorm(18), nrow = 3, ncol = 6)
m2<- matrix(runif(24), nrow = 6, ncol = 4)

m %*% m2

[,1]      [,2]       [,3]        [,4]      
[1,] 0.1019770 -1.4882742 -0.04253161 -1.0473302
[2,] 1.4559452  1.5378115  1.21868800  1.1429936
[3,] 0.1730759 -0.9732007  0.19594472 -0.1857031

In [7]:
# Challenge 2: Create a third matrix and sum with the first one elementwise

m3<-matrix(1:18, 3,6)

m+m3

[,1]     [,2]     [,3]     [,4]      [,5]     [,6]    
[1,] 2.218585 4.013380 5.872324  8.666113 14.15629 15.03336
[2,] 2.642242 5.544468 8.427363 11.753570 14.22215 17.44089
[3,] 3.080591 4.910755 8.440116 11.183229 16.18931 18.31263

In [8]:
m3

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    4    7    10   13   16  
[2,] 2    5    8    11   14   17  
[3,] 3    6    9    12   15   18

In [9]:
m

[,1]       [,2]        [,3]       [,4]       [,5]      [,6]      
[1,] 1.21858533  0.01338031 -1.1276756 -1.3338874 1.1562905 -0.9666447
[2,] 0.64224199  0.54446765  0.4273626  0.7535702 0.2221548  0.4408884
[3,] 0.08059057 -1.08924521 -0.5598836 -0.8167712 1.1893089  0.3126307

## Data.frames

In [10]:
# Challenge 1: Create a data.frame of 6 rows, each element would be a pair of name and an age (at your choice, but one has to be 'bob')
mydf=data.frame(name=c('bob','robert','dad','angela','liz','ray'),
                age=c(25,32,53,48,23,43)
                )
mydf

name   age
1 bob    25 
2 robert 32 
3 dad    53 
4 angela 48 
5 liz    23 
6 ray    43

In [11]:
# Challenge 2: Print bob's age: use dplyr or data.table, at your choice

mydf %>% filter(name=='bob')%>%select(age) %>% unlist()


mydt<-as.data.table(mydf)
mydt[name=='bob', 'age'] %>% unlist()


age 
 25

age 
 25

In [12]:
# Challenge 3: Extract names of people whose age is under certain value
Limit=40

# Standard data.frame use
mydf[mydf$age<Limit,]

# dplyr
mydf %>% filter(age<Limit)

# data.table
mydt[age<Limit]

name   age
1 bob    25 
2 robert 32 
5 liz    23

name   age
1 bob    25 
2 robert 32 
3 liz    23

name   age
1 bob    25 
2 robert 32 
3 liz    23

In [13]:
# Challenge 4: Using our data.frame of 'name' and 'age' columns 
# create a new column year of birth, computed from age

# Standard R
mydf$year<-2021-mydf$age
mydf

# dplyr
mydf<-mydf %>%mutate(year=2021-age)
mydf

# data.table
mydt[,year:=2021-age]
mydt

name   age year
1 bob    25  1996
2 robert 32  1989
3 dad    53  1968
4 angela 48  1973
5 liz    23  1998
6 ray    43  1978

name   age year
1 bob    25  1996
2 robert 32  1989
3 dad    53  1968
4 angela 48  1973
5 liz    23  1998
6 ray    43  1978

name   age year
1 bob    25  1996
2 robert 32  1989
3 dad    53  1968
4 angela 48  1973
5 liz    23  1998
6 ray    43  1978

## Functions

In [33]:
## Now we will use this data.frame of real estate rents
my_re<-data.frame(
    code=c('ID001','ID002','ID003','ID004','ID005','ID006'),
    city=c('Barcelona','Paris','Rome','London','Barcelona','Paris'),
    sq_mt=c(80,75,95,81,103,89),
    value=c(1100, 1600, 1100,2000,1800,1900)
)
my_re_dt<-as.data.table(my_re) # to practice data.table

In [34]:
# Challenge 1: silly example: Build a function that receives two numbers 'sq_mt' and 'value'
# and returns the ratio value/sq_mt

# Test it with this example
sq_mt=104
value=1550

# your code here
compute_ratio<-function(sq_mt, value){
    return (value/sq_mt)
}

compute_ratio(sq_mt, value)

# check that also works also with vectors instead of numbers

[1] 14.90385

In [35]:
# Challenge 2: Apply previous function to all rows in our df
# hint: this function also works in a vectorized way

# Standard R
my_re$ratio<-compute_ratio(my_re$sq_mt,my_re$value)
my_re

# dplyr
my_re<-my_re %>% mutate(ratio=compute_ratio(sq_mt,value))
my_re

# data.table
my_re_dt[,ratio := compute_ratio(sq_mt,value)]
my_re_dt


code  city      sq_mt value ratio   
1 ID001 Barcelona  80   1100  13.75000
2 ID002 Paris      75   1600  21.33333
3 ID003 Rome       95   1100  11.57895
4 ID004 London     81   2000  24.69136
5 ID005 Barcelona 103   1800  17.47573
6 ID006 Paris      89   1900  21.34831

code  city      sq_mt value ratio   
1 ID001 Barcelona  80   1100  13.75000
2 ID002 Paris      75   1600  21.33333
3 ID003 Rome       95   1100  11.57895
4 ID004 London     81   2000  24.69136
5 ID005 Barcelona 103   1800  17.47573
6 ID006 Paris      89   1900  21.34831

code  city      sq_mt value ratio   
1 ID001 Barcelona  80   1100  13.75000
2 ID002 Paris      75   1600  21.33333
3 ID003 Rome       95   1100  11.57895
4 ID004 London     81   2000  24.69136
5 ID005 Barcelona 103   1800  17.47573
6 ID006 Paris      89   1900  21.34831

In [38]:
# Challenge 3: Build then a function that receives as input one value of square meters, and a reference data.frame 
#  and yields the average rent of real estates with area above these square meters
# apply to our data.frame
Min<-83

cond_avg<-function(Min, df){
    # Standard R
#     aux<-df[df$sq_mt>Min,]
#     avg<-mean(aux$value,na.rm=T)
    
    # dplyr
    avg<-df %>%filter(sq_mt>Min) %>% summarize(Avg= mean(value,na.rm=T)) %>% unlist()
    
    return (avg)
}

cond_avg_dt<-function(Min, dt){
    
    # data.table
    avg<-dt[sq_mt>Min][,.(Avg=mean(value,na.rm=T))]
    avg<-unlist(avg)
    
    return (avg)
}

cond_avg(Min,my_re)
cond_avg_dt(Min,my_re_dt)

Avg 
1600

Avg 
1600

In [40]:
my_re

code  city      sq_mt value ratio   
1 ID001 Barcelona  80   1100  13.75000
2 ID002 Paris      75   1600  21.33333
3 ID003 Rome       95   1100  11.57895
4 ID004 London     81   2000  24.69136
5 ID005 Barcelona 103   1800  17.47573
6 ID006 Paris      89   1900  21.34831

In [43]:
# Challenge 4: Modify previous function, so that handles subsetting by cities
# and in case the city is not listed, yields an error message
Min<-83
my_city<-'Barcelona'

cond_avg<-function(Min, my_city, df){
    
    if (my_city %in% df$city){
        # Standard R
        aux<-df[df$sq_mt>Min & df$city==my_city,]
        avg<-mean(aux$value,na.rm=T)

        # dplyr
        avg<-df %>%filter(sq_mt>Min & city==my_city) %>% summarize(Avg= mean(value,na.rm=T)) %>% unlist()

        return (avg)
        
    } else {
        return ('City not listed')
    }
    

}

cond_avg_dt<-function(Min, my_city, dt){    
    
    if (my_city %in% dt$city){
    
        # data.table
        avg<-dt[sq_mt>Min & city==my_city][,.(Avg=mean(value,na.rm=T))]
        avg<-unlist(avg)
    
        return (avg)
    } else {
        return ('City not listed')
    }
}

cond_avg(Min,'Barcelona', my_re)
cond_avg_dt(Min,'Barcelona',my_re_dt)

Avg 
1800

Avg 
1800

## Data analysis

Use either dplyr+tidyr or data.table functions, at your wish.

We will use [mtcars dataset](https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/mtcars).

In [59]:
data(mtcars)
head(mtcars,10)
mtcars$name<-rownames(mtcars)

mtcars_dt<-as.data.table(mtcars)

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360        14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D         24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230          22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280          19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4

In [60]:
# Challenge 1: Report average consumption (mpg) of vehicles depending on the combination of cylinder number and transmission (am).

# dplyr
mtcars %>% group_by(cyl, am) %>% summarize(avg_mpg=mean(mpg,na.rm=T)) %>% arrange(avg_mpg)

# data.table
mtcars_dt[,.(avg_mpg=mean(mpg,na.rm=T)),by=.(cyl,am)][order(avg_mpg)]

cyl am avg_mpg 
1 8   0  15.05000
2 8   1  15.40000
3 6   0  19.12500
4 6   1  20.56667
5 4   0  22.90000
6 4   1  28.07500

cyl am avg_mpg 
1 8   0  15.05000
2 8   1  15.40000
3 6   0  19.12500
4 6   1  20.56667
5 4   0  22.90000
6 4   1  28.07500

In [61]:
# Challenge 2: Report top10 cars sorted by decreasing number of cylinders and weight '
# dplyr
mtcars %>% arrange(-cyl, -wt) %>% head(10)

# data.table
mtcars_dt[order(-cyl,-wt),head(.SD,10)]

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb name               
1  10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4    Lincoln Continental
2  14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4    Chrysler Imperial  
3  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4    Cadillac Fleetwood 
4  16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3    Merc 450SE         
5  19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2    Pontiac Firebird   
6  13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4    Camaro Z28         
7  15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3    Merc 450SLC        
8  17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3    Merc 450SL         
9  14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4    Duster 360         
10 15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8    Maserati Bora

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb name               
1  10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4    Lincoln Continental
2  14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4    Chrysler Imperial  
3  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4    Cadillac Fleetwood 
4  16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3    Merc 450SE         
5  19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2    Pontiac Firebird   
6  13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4    Camaro Z28         
7  15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3    Merc 450SLC        
8  17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3    Merc 450SL         
9  14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4    Duster 360         
10 15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8    Maserati Bora

In [81]:
# Challenge 3: Add a couple more of cars (just generate fake data) and bind to to dataset
# you can use variations around mean value to generate those
# don't worry if you use float instead of integer, doesn't need to be realistic

sample<-colMeans(mtcars%>%select(-name))
sample2<-apply(mtcars%>%select(-name),2, quantile, probs=c(0.4,0.6))
sample<-rbind(sample, sample2)
sample<-as.data.frame(sample)
sample$name<-paste0('NewModel',1:nrow(sample))

mtcars2<-rbind(mtcars, sample)
tail(mtcars2)

mpg      cyl    disp     hp       drat     wt      qsec    
Ferrari Dino  19.70000 6.0000 145.0000 175.0000 3.620000 2.77000 15.50000
Maserati Bora 15.00000 8.0000 301.0000 335.0000 3.540000 3.57000 14.60000
Volvo 142E    21.40000 4.0000 121.0000 109.0000 4.110000 2.78000 18.60000
sample        20.09062 6.1875 230.7219 146.6875 3.596563 3.21725 17.84875
40%           17.92000 6.0000 160.0000 110.0000 3.354000 3.15800 17.34000
60%           21.00000 8.0000 275.8000 165.0000 3.818000 3.44000 18.18000
              vs     am      gear   carb   name         
Ferrari Dino  0.0000 1.00000 5.0000 6.0000 Ferrari Dino 
Maserati Bora 0.0000 1.00000 5.0000 8.0000 Maserati Bora
Volvo 142E    1.0000 1.00000 4.0000 2.0000 Volvo 142E   
sample        0.4375 0.40625 3.6875 2.8125 NewModel1    
40%           0.0000 0.00000 3.0000 2.0000 NewModel2    
60%           1.0000 0.60000 4.0000 3.0000 NewModel3

In [91]:
# Challenge 4: Try to add tax info, assuming that only depends on cyl
# Create a new data.frame or data.table with unique values of column cyl and then add a 'tax' value
# (generate a fake tax quantity per cilinder)
# Then merge this new df with mtcars

df<-data.frame(
                cyl=sort(unique(mtcars$cyl)), 
               tax=seq(100,200,length.out = length(unique(mtcars$cyl)))
                      )
df

# tidyr
mtcars<- mtcars %>% left_join(df, by='cyl')
head(mtcars)

# data.table
mtcars_dt<- merge(mtcars_dt,df, all.x=T, by='cyl')
head(mtcars_dt)

cyl tax
1 4   100
2 6   150
3 8   200

mpg  cyl disp hp  drat wt    qsec  vs am gear carb name              tax
1 21.0 6   160  110 3.90 2.620 16.46 0  1  4    4    Mazda RX4         150
2 21.0 6   160  110 3.90 2.875 17.02 0  1  4    4    Mazda RX4 Wag     150
3 22.8 4   108   93 3.85 2.320 18.61 1  1  4    1    Datsun 710        100
4 21.4 6   258  110 3.08 3.215 19.44 1  0  3    1    Hornet 4 Drive    150
5 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2    Hornet Sportabout 200
6 18.1 6   225  105 2.76 3.460 20.22 1  0  3    1    Valiant           150

cyl mpg  disp  hp drat wt    qsec  vs am gear carb name           tax
1 4   22.8 108.0 93 3.85 2.320 18.61 1  1  4    1    Datsun 710     100
2 4   24.4 146.7 62 3.69 3.190 20.00 1  0  4    2    Merc 240D      100
3 4   22.8 140.8 95 3.92 3.150 22.90 1  0  4    2    Merc 230       100
4 4   32.4  78.7 66 4.08 2.200 19.47 1  1  4    1    Fiat 128       100
5 4   30.4  75.7 52 4.93 1.615 18.52 1  1  4    2    Honda Civic    100
6 4   33.9  71.1 65 4.22 1.835 19.90 1  1  4    1    Toyota Corolla 100

In [93]:
# Challenge 5: Report in alphabetical order the name of cars that have maximum tax value, 
# but showing only those ones wit non-automatic transmission

# dplyr
mtcars %>% filter(am==0 & tax==max(tax)) %>% arrange(name) 

# data.table
mtcars_dt[am==0 & tax==max(tax)][order(name)]

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb name                tax
1  15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2    AMC Javelin         200
2  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4    Cadillac Fleetwood  200
3  13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4    Camaro Z28          200
4  14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4    Chrysler Imperial   200
5  15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2    Dodge Challenger    200
6  14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4    Duster 360          200
7  18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2    Hornet Sportabout   200
8  10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4    Lincoln Continental 200
9  16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3    Merc 450SE          200
10 17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3    Merc 450SL          200
11 15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3    Merc 450SLC         200
12 19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2    Pontiac Firebird    200

cyl mpg  disp  hp  drat wt    qsec  vs am gear carb name                tax
1  8   15.2 304.0 150 3.15 3.435 17.30 0  0  3    2    AMC Javelin         200
2  8   10.4 472.0 205 2.93 5.250 17.98 0  0  3    4    Cadillac Fleetwood  200
3  8   13.3 350.0 245 3.73 3.840 15.41 0  0  3    4    Camaro Z28          200
4  8   14.7 440.0 230 3.23 5.345 17.42 0  0  3    4    Chrysler Imperial   200
5  8   15.5 318.0 150 2.76 3.520 16.87 0  0  3    2    Dodge Challenger    200
6  8   14.3 360.0 245 3.21 3.570 15.84 0  0  3    4    Duster 360          200
7  8   18.7 360.0 175 3.15 3.440 17.02 0  0  3    2    Hornet Sportabout   200
8  8   10.4 460.0 215 3.00 5.424 17.82 0  0  3    4    Lincoln Continental 200
9  8   16.4 275.8 180 3.07 4.070 17.40 0  0  3    3    Merc 450SE          200
10 8   17.3 275.8 180 3.07 3.730 17.60 0  0  3    3    Merc 450SL          200
11 8   15.2 275.8 180 3.07 3.780 18.00 0  0  3    3    Merc 450SLC         200
12 8   19.2 400.0 175 3.08 3.845 17.05 0  0  3    2    Pontiac Firebird    200

In [109]:
# Challenge 6: Build a matrix with cylinders as columns and gears as rows, and mpg as value of each cell
# hint: first compute average by groups, then reshape!

# dplyr + tidyr
aux<- mtcars %>% group_by(cyl,gear) %>% summarize(avg_mpg=mean(mpg)) %>%
    spread(key=cyl, value = avg_mpg) # key= which variable I want to use to create column groups
matrix<-as.matrix(aux%>% select(-gear))
rownames(matrix)<-paste0('Gear_',aux$gear)
colnames(matrix)<-paste0('Cyl_',unique(mtcars$cyl) )
matrix

# data.table
aux2<- mtcars_dt[,.(avg_mpg=mean(mpg)),.(cyl,gear)]
aux2<-dcast(aux2, gear ~ cyl, value.var = "avg_mpg")
matrix2<-as.matrix(aux2[,-c('gear')])
rownames(matrix2)<-paste0('Gear_',aux$gear)
colnames(matrix2)<-paste0('Cyl_',unique(mtcars_dt$cyl) )
matrix2


Cyl_6  Cyl_4 Cyl_8
Gear_3 21.500 19.75 15.05
Gear_4 26.925 19.75    NA
Gear_5 28.200 19.70 15.40

Cyl_4  Cyl_6 Cyl_8
Gear_3 21.500 19.75 15.05
Gear_4 26.925 19.75    NA
Gear_5 28.200 19.70 15.40

In [112]:
# Challenge 7: Report data from all cars whose name starts by 'M' and ends with a number 
# hint: use grepl

# standard R
mtcars[grepl('^[Mm].+[0-9]$',mtcars$name),]

# dplyr

mtcars %>% filter(grepl('^[Mm].+[0-9]$',name))

# data.table
mtcars_dt[grepl('^[Mm].+[0-9]$',name),]

mpg  cyl disp  hp  drat wt   qsec  vs am gear carb name      tax
1  21.0 6   160.0 110 3.90 2.62 16.46 0  1  4    4    Mazda RX4 150
9  22.8 4   140.8  95 3.92 3.15 22.90 1  0  4    2    Merc 230  100
10 19.2 6   167.6 123 3.92 3.44 18.30 1  0  4    4    Merc 280  150

mpg  cyl disp  hp  drat wt   qsec  vs am gear carb name      tax
1 21.0 6   160.0 110 3.90 2.62 16.46 0  1  4    4    Mazda RX4 150
2 22.8 4   140.8  95 3.92 3.15 22.90 1  0  4    2    Merc 230  100
3 19.2 6   167.6 123 3.92 3.44 18.30 1  0  4    4    Merc 280  150

cyl mpg  disp  hp  drat wt   qsec  vs am gear carb name      tax
1 4   22.8 140.8  95 3.92 3.15 22.90 1  0  4    2    Merc 230  100
2 6   21.0 160.0 110 3.90 2.62 16.46 0  1  4    4    Mazda RX4 150
3 6   19.2 167.6 123 3.92 3.44 18.30 1  0  4    4    Merc 280  150